### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by mamadoo**

### CODE REVIEW

**Comment by mamadoo** [comment]
Dooste aziz shoma bayad framework ro biyarid roye github va ya heroku va ...

**Comment by vahidalvandi** [comment]
alan roye github mizbany mishe

**Comment by mamadoo** [comment]
Manzoram ine ke be jaye https://roxana.webineh.net/ bayad az yechizi mesle roxana.github.io estefade konid
bayad az pages.github.com baraye inkar estefade konid
free has

**Comment by vahidalvandi** [comment]
bale,dar tanzimat ejaze in karo mide ama dynamic nist , ye barasikardam didm ye cms be name jekly bayad estefade konam ama man rosh kar nakardam agar shoma ashnai dar morad nasb in cms darid rahnami konid hatman anjam khaham dad.

ba tashakor

**Comment by mamadoo** [comment]
Doost aziz dalili nadare ke site dynamic dashte bashid....static kafiye...code haye shoma faghat css hastan va faghat mikhayd zaher ro neshon bedid be user ha
in url ke alan gozashtin moshkel dare va redirect mishe
age mishe roye github safhe besazid

**Pull request merged**
